### ISSUE TITLE
Strona główna - zespół

### ISSUE THREAD

**Issue by WojtekSanko** [komitywa/komitywa.org#22]
Poniżej zdjęcia z misją, chcę zobaczyć nasz zespół.
Zdjęcia i krótkie opisy. Z linkami do linkedin lub fb. 
Tomek, Wojtek, Gracjan, Magda oraz Marta.
Opisy i zdjęcia załączę.

**Comment by magul** [comment]
* `Kwadraty 6cm na 6cm w rzędach obok i poniżej. 3 na szerokość strony.` Ile tych kwadratów będzie? 6cm na 6cm to jest bardzo zła miara - jak to się ma zachowywać np. na telefonie? 
 * `każdy kwadrat ze zdjęciem, na których jest napisane jedno zdanie` po ustaleniu, ile tych kwadratów jest będziemy potrzebować zdjęć, które w tych kwadratach będą się znajdować oraz tekstów, które mają być w nie wpisane,
 * `Tekst ... jest wpisany w biały prostokąt` - co to jest za prostokąt? to jest coś w tym zdjęciu? to ma być coś dookoła zdjęcia?
 * Czy te prostokąty jakoś się łączą z zawartością strony `nasze działania`?

**Comment by magul** [comment]
Poprosimy jeszcze linki do FB i LinkedIn.

Dodatkowo należałoby dodać linki do kont na githubie.

No i jeszcze dla Marty to jednak trochę za szybko - z Martą poczekamy.
